### ISSUE TITLE
Picto : format + language + copyright

### ISSUE THREAD

**Issue by RxnDbr** [anthill/6elementApp#4]
I have juste add wastes picto (46pictures, 2.2 mo, jpg) in 6elementApp but @DavidBruant  told me to write an issue because: 
- jpg is not the best extension 
- waste type is written on the picture  : 
  - it is a problem if we want to change the style
  - it is avaiable only in France
- It is written on ADEME [website](http://www.optigede.ademe.fr/decheteries) that it is free of copyright but there is no licence

**Comment by vallettea** [comment]
David's remarks are justified but I guess
- we'll start with France
- people have already have long thoughts about how to represent these categories.
- we could ask for their permission

What I suggest is to start from these, vectorise them in svg, keeping only the log and commit the logo. This way we could style and scale them at will.
Roxane, I'll help you to do that tomorrow.

**Comment by vallettea** [comment]
@DavidBruant could help roxane remove these image from github ?

**Comment by DavidBruant** [comment]
> What I suggest is to start from these

Same opinion. This issue is a follow up to @RxnDbr PR. This idea of this issue was to trace the limitations of the current choices, but we should move forward.

**Comment by DavidBruant** [comment]
Why removing the images? We need them, don't we? Where should they be stored if not in the repo?

**Comment by vallettea** [comment]
I guess we can only store on file with svg paths ?

**Comment by DavidBruant** [comment]
Ok. Let's see if that makes that big a difference.

**Comment by RxnDbr** [comment]
357.96ko, quite better :+1: 
We'll remove text tomorrow @vallettea

**Comment by bleucitron** [comment]
Should we close this ?

**Comment by vallettea** [comment]
Yes
