### ISSUE TITLE
Code review 130715

### ISSUE THREAD

**Issue by bleucitron** [anthill/6elementApp#5]
Okay, here are some thoughts on the code state as for July 13th 2015:
# Critical

You shall NEVER EVER EVER :imp: do something after a `setState` call. This function calls a render of all the Application (that is, from the upper part, which initiates in `main.js`), and then what's after will not executed.
https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/Application.js#L74-L81
https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/BooleanFilter.js#L28-L31

We will review this part together, this is probably why you can't get your fav prop to get working as it should be.
# Structural

You should try to organize a little more the code structure.

**In `main.js`:**
The idea is that this file should require all the infos that the App needs, perform basic calculations, and then launch the App. It should remain as plain and simple as possible. So no data you be hardcoded in there.
Hence,
https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/main.js#L20-L69 should be in a different file, maybe even in a different folder (in `img/` for instance).
Also https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/main.js#L72-L213 represents an entry taken from the database. It should be in an file like `fakeRCentry.js` or equivalent.

**In `utils.js`**
We have a little brawl with @DavidBruant on this matter, but maybe something in between could be interesting.
I like having all my basic utils functions in one unique place, but he finds it more practical to have one file for each. Maybe we could separate functions that are really really basic and universal (like time management, list handling, ...) from the ones dedicated to this particular project (usually a little more complex). The basic functions would all go in one unique `utils.js` file, whereas the dedicated functions would have their own file. All these could all go in a `utils/` folder. I'd like to have @DavidBruant 's thoughts on this.
Also, you should be more explicit regarding your functions' names (these are only ideas):
`numDay` should be `getDayNumber`
`levelCalc` should be `getCrowdLevel`
...

**In general**
Maybe get rid of useless folders, like `example` or `data` (i'm not sure, but i don't think they're relevant anymore, to be discussed)
# Cosmetics

**In general**
Don't leave too many useless comments, like https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/BooleanFilter.js#L36-L43
or
https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/Application.js#L87-L103
You should review your code to clean those up.

Plus, don't forget to update your props/state headers for each component, so that any newbie (like me) understands in one blink what is at stake where reading a component's code. For instance https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/Level.js#L8-L18, this doesn't seem up to date.

**In `Application.js`**
In general constants should be outside the actual Component. https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/Application.js#L48-L50 are constants, and should not be inside `render`, nor anywhere after `var App = ...`

Pay attention to variable names :p `avaiable` is not a word !
https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/Application.js#L184-L185
Same for `lisAvaiable`.

Plus, `startDay` should probably be `dayStart`or `startOfDay`, same for `endDay`
https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/Levels.js#L42-L48

This could probably be prettier, we are not supposed to use this `for` syntax. https://github.com/anthill/6elementApp/blob/91649ec144dc2b7711808010f1073fac4920b785/src/Components/Levels.js#L52-L70 :)

**Comment by vallettea** [comment]
:+1:

**Comment by DavidBruant** [comment]
> You shall NEVER EVER EVER :imp: do something after a setState call. This function calls a render of all the Application (that is, from the upper part, which initiates in main.js), and then what's after will not executed.

Yes and no. What's after will be executed, but that's part of the problem. In this case, what's executed is telling the parent about the state change. Suddenly, the state lies in 2 places: the parent and the child. The parent may re-render the child (so the data is in the props) or the child (state). Classic debates. The short version is that each piece of application state should only be handled in one way (props xor state).

> Maybe we could separate functions that are really really basic and universal (like time management, list handling, ...) from the ones dedicated to this particular project (usually a little more complex)

This distinction is the good one. Some functions make sense only in the 6element context, other are generic.
IMHO, the project-specific parts should go somewhere else than utils. Maybe alongside the model, maybe somewhere else. It's not clear, but it's distinct from utils.
As far as generic functions, ideally, we'd pick them from npm (lodash or else), if the functions we need aren't there, let's have a util.js file indeed.

I agree on the rest.

**Comment by bleucitron** [comment]
Fixed during July, can't remember when exactly :p
